id:       default
name:     default
description: 主卡组现开(50选23~26) + 额外轮抓(3×4)
uses:
  - pool: default
    alias: C
patterns:
  - mode: sealed
    minpicks: 1
    maxpicks: 1
    configs:  { uniq: true }
    patterns:
      - compose:
        - rate: 1
          parts:
            - n: 3
              filter: T1&G1

  # main deck...
  - mode: sealed
    minpicks: 23
    maxpicks: 26
    patterns:
      - compose:
          - rate: 1
            parts:
              - n:      2
                filter: T2&G1&Main
              - n:      3
                filter: T3&G1&Main
              - n:      5
                filter: T4&G1&Main
          - rate: 3
            parts:
              - n:      2
                filter: T2&G1&Main
              - n:      4
                filter: T3&G1&Main
              - n:      4
                filter: T4&G1&Main
          - rate: 2
            parts:
              - n:      2
                filter: T2&G1&Main
              - n:      5
                filter: T3&G1&Main
              - n:      3
                filter: T4&G1&Main
      - compose:
          - rate: 1
            parts:
              - n: 2
                filter: Main&!T1&G1&(SPELL|TRAP)
      - compose:
          - rate: 1
            parts:
              - n: 3
                filter: Main&G2&(SPELL|TRAP)
      - compose:
          - rate: 1
            parts:
              - n: 4
                filter: T3&G1&Main
      - compose:
          - rate: 1
            parts:
              - n:      20
                filter: T5&G1&Main
      - compose:
          - rate: 1
            parts:
              - n:      15
                filter: T5&G1&Main

  - mode: draft
    shifts: [1, 1, 1]
    repeats: { fork: 3 }
    patterns:
      - compose:
        - rate: 1
          parts:
            - n: 2
              filter: 'LINK&G1'
            - n: 2
              filter: 'LINK&G2'
        - rate: 2
          parts:
            - n: 3
              filter: 'LINK&G1'
            - n: 1
              filter: 'LINK&G2'

      - compose:
        - rate: 1
          parts:
            - n: 3
              filter: 'SYNCHRO&G1'
            - n: 1
              filter: 'SYNCHRO&G2'

      - compose:
        - rate: 1
          parts:
            - n: 2
              filter: 'XYZ&G1'
            - n: 2
              filter: 'XYZ&G2'
        - rate: 2
          parts:
            - n: 3
              filter: 'XYZ&G1'
            - n: 1
              filter: 'XYZ&G2'
