# This is a basic workflow to help you get started with Actions

name: build-and-release

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@master

      # Tag it
      - uses: EndBug/latest-tag@v1.4.0

      # Setup node env
      - uses: actions/setup-node@master
        with:
          node-version: 14.16.1
          cache: yarn

      # Install deps
      - name: install-deps
        run: |
          npm i -g lerna lerna
          lerna bootstrap

      # Build the app!
      - name: prepare
        run: lerna run build   --scope @picky/shared
      - name: build
        working-directory: ./modules/app
        run: yarn package -w

      # Release
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: auto release
          body: auto release
          allowUpdates: true
          tag: latest
          prerelease: true
          artifacts: "./modules/app/release/build/*.exe"
